services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  bot:
    build:
      context: .
      args:
        - APP_VERSION=0.2.0
    restart: unless-stopped
    command: python -m app.main
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./fastf1_cache:/app/fastf1_cache
    depends_on:
      - redis

  web:
    build:
      context: .
      args:
        - APP_VERSION=0.3.0
    restart: unless-stopped
    entrypoint: ["/app/entrypoint_web.sh"]
    command: ["python", "run_web.py"]
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./fastf1_cache:/app/fastf1_cache
      - static_content:/app/front/dist
    depends_on:
      - redis
      - bot

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /root/FormulaOneBot/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web

#  tunnel:
#    image: cloudflare/cloudflared:latest
#    restart: unless-stopped
#    command: tunnel --url http://nginx:80
#    depends_on:
#      - nginx

volumes:
  redis_data:
  # Объявляем volume для синхронизации фронтенда
  static_content: